In [6]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time
import pandas as pd
import os

chrome_driver_path = 'D:\Project\Liga 1 Indonesia\Liga-1-Indonesia\chromedriver-win64\chromedriver.exe'

# Setup Driver
options = webdriver.ChromeOptions()
#options.add_argument("--headless") # Biar Chrome-nya tidak dibuka (Jalan di belakang)
service = Service(chrome_driver_path)
driver = webdriver.Chrome(service=service, options=options)
driver.maximize_window() # Kalo headless, ini nggak berguna

folder_path = "Link Pemain"
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    print(file)
    data = pd.read_csv(file_path)
    link_pemain = data['Link Pemain'].tolist()
    data_pemain = []
    
    for link in link_pemain[:3]:
        driver.get(link)
        print(link)
        time.sleep(2)

        def get_xpath(xpath):
            try:
                return driver.find_element(By.XPATH, xpath).text.strip()
            except:
                return None

        data = {
            'Nama Pemain': get_xpath('/html/body/div[2]/div/div/div/div[2]/h1[2]'),
            'Nomor Punggung': get_xpath('/html/body/div[2]/div/div/div/div[2]/h1[1]'),
            'Klub': get_xpath('/html/body/div[2]/section/div/div/div/div[1]/div/div/table/tbody/tr[3]/td[2]'),
            'Posisi': get_xpath('/html/body/div[2]/section/div/div/div/div[1]/div/div/table/tbody/tr[4]/td[2]'),
            'Usia': get_xpath('/html/body/div[2]/section/div/div/div/div[1]/div/div/table/tbody/tr[5]/td[2]'),
            'Negara': get_xpath('/html/body/div[2]/section/div/div/div/div[1]/div/div/table/tbody/tr[6]/td[2]'),

            'Penampilan': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[1]/ul/li[1]/h3'),
            'Penyelamatan': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[1]/ul/li[3]/h3'),

            'Gol': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[1]/div/ul/li[1]/p/span'),
            'Tembakan': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[1]/div/ul/li[2]/p/span'),
            'Tembakan Tepat Sasaran': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[1]/div/ul/li[3]/p/span'),

            'Assist': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div/ul/li[1]/p/span'),
            'Umpan Sukses': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div/ul/li[2]/p/span'),

            'Tekel': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[3]/div/ul/li[1]/p/span'),
            'Intersepsi': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[3]/div/ul/li[2]/p/span'),
            'Sapuan': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[3]/div/ul/li[3]/p/span'),

            'Kartu Kuning': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[4]/div/ul/li[1]/p/span'),
            'Kartu Merah': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[4]/div/ul/li[2]/p/span'),
            'Pelanggaran': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[4]/div/ul/li[3]/p/span'),
            'Offside': get_xpath('/html/body/div[2]/section/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[4]/div/ul/li[4]/p/span'),
        }

        print(f"Mengambil data: {data['Nama Pemain']}")
        data_pemain.append(data)

    nama_klub = file.replace(".csv", "")
    df_pemain = pd.DataFrame(data_pemain)
    df_pemain.to_csv(f"Data Pemain/{nama_klub}-PEMAIN.csv", index=False)

driver.quit()

AREMA_FC.csv
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/bayu_aji?token=UDAuMTkwMTM5NTE3MQ==
Mengambil data: BAYU AJI
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/syaeful_anwar?token=UDAuMTcxMDA4NTE3MQ==
Mengambil data: SYAEFUL A.
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/thales__natanael_lira_de_matos?token=UDAuNjcyOTYyMzI=
Mengambil data: THALES LIRA
BALI_UNITED_FC.csv
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/adilson_aguero_dos_santos?token=UDAuNzgzMTAzMTI=
Mengambil data: MARINGÁ
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/agung_mannan?token=UDAuODkzNTk1MTcx
Mengambil data: AGUNG M.
https://ligaindonesiabaru.com/clubs/singleplayer/bri_liga_1_2024-25/yusef_elias_dolah?token=UDAuNTc0MzIyMzI=
Mengambil data: E. DOLAH

In [7]:
data_arema = pd.read_csv('Data Pemain/AREMA_FC-PEMAIN.csv')
data_arema

,Nama Pemain,Nomor Punggung,Klub,Posisi,Usia,Negara,Penampilan,Penyelamatan,Gol,Tembakan,Tembakan Tepat Sasaran,Assist,Umpan Sukses,Tekel,Intersepsi,Sapuan,Kartu Kuning,Kartu Merah,Pelanggaran,Offside
0,BAYU AJI,3,AREMA FC,BELAKANG,25,Indonesia,4,0,0,0,0,0,69/76,4,8,9,2,0,5,0
1,SYAEFUL A.,4,AREMA FC,BELAKANG,31,Indonesia,5,0,0,1,0,0,99/108,4,11,8,0,0,3,0
2,THALES LIRA,5,AREMA FC,BELAKANG,32,Brazil,24,1,1,16,9,1,588/681,24,78,54,4,1,28,1

In [8]:
data_bali = pd.read_csv('Data Pemain/BALI_UNITED_FC-PEMAIN.csv')
data_bali

,Nama Pemain,Nomor Punggung,Klub,Posisi,Usia,Negara,Penampilan,Penyelamatan,Gol,Tembakan,Tembakan Tepat Sasaran,Assist,Umpan Sukses,Tekel,Intersepsi,Sapuan,Kartu Kuning,Kartu Merah,Pelanggaran,Offside
0,MARINGÁ,1,BALI UNITED FC,P. GAWANG,35,Brazil,25,79,0,0,0,0,308/397,0,2,8,3,0,0,0
1,AGUNG M.,47,DEWA UNITED FC,BELAKANG,27,Indonesia,7,0,0,3,0,1,57/73,7,6,5,3,0,3,1
2,E. DOLAH,4,BALI UNITED FC,BELAKANG,32,Thailand,26,0,0,15,3,1,801/944,30,110,115,7,0,53,0